apiVersion: v1
kind: ConfigMap
metadata:
  name: idm
data:
  IDM_ENVCONFIG_DIRS: /opt/openidm/resolver
  JAVA_OPTS: -server -XX:+PrintFlagsFinal -XX:MaxRAMPercentage=75
  LOGGING_PROPERTIES: /var/run/openidm/logging/logging.properties
  OPENIDM_ANONYMOUS_PASSWORD: anonymous
  OPENIDM_CLUSTER_REMOVE_OFFLINE_NODE_STATE: "true"
  OPENIDM_CONFIG_REPO_ENABLED: "false"
  PROJECT_HOME: /opt/openidm