# This is a small "admin" pod that just pauses and waits for 
# someone to exec into the image. Used for debugging, kicking off remote tasks, etc..
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsadmin
  labels:
    app: dsadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsadmin
  template:
    metadata: 
      labels:
        app: dsadmin
    spec:
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      initContainers:
      # When the NFS share has just been created it is owned by root. We need to run as root, create
      # a top level folder for backups, and chown the permisions to the forgerock user.
      - name: chmod
        image: busybox
        command: ['sh', '-c', 'chown 11111 /bak/; chmod 775 /bak/*']
        volumeMounts:
        - name: backup
          mountPath: /bak
      containers:
      - name: opendj
        image:  {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # envFrom:
        # - configMapRef:
        #     name: {{ .Values.instance }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPENDJ_JAVA_ARGS
          value: "-Xmx256m"
        volumeMounts:
        - name: backup
          mountPath: /opt/opendj/bak
        # volumeMounts:
        # - name: dj-secrets
        #   mountPath: /var/run/secrets/opendj
        args: [ "pause" ]
        resources:
          requests:
            memory: 300Mi
          limits:
            memory: 350Mi
      volumes:
      - name: backup
        persistentVolumeClaim:
          claimName: "{{ .Values.backup.pvcName }}"
      # There is a single dsadmin instance for all ds servers - so we don't mount any secret for the 
      # directory manager password. TOOD: We can revist this.
      # volumes:
      #   - name: dj-secrets
      #     secret:
      #       secretName: {{ .Values.instance }}