apiVersion: v1
kind: Service
metadata:
  labels:
    app: openig-openig
    component: openig
    vendor: forgerock
  name: openig
spec:
  ports:
  - name: openig
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: openig
  type: ClusterIP
