apiVersion: v1
kind: ConfigMap
metadata:
  name: amster
data:
  # Note: This is a default value that may get overwritten by the platform-config ConfigMap
  CTS_STORES: "ds-cts-0.ds-cts:1389"
  IDREPO_STORES: "ds-idrepo-0.ds-idrepo:1389"
  # Sets the password for AM prometheus configuration. Not clear if we need this here or should
  # move
  PROMETHEUS_PASSWORD: prometheus
