{{ if .Values.adminContainer }}
# This is a small optional "admin" pod that just pauses and waits for 
# someone to exec into the image. Used for debugging
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.djInstance }}-admin
spec:
  containers:
  - name: opendj
    image:  {{ .Values.image.repository }}/{{ .Values.component }}:{{ .Values.image.tag }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    envFrom:
    - configMapRef:
        name: {{ .Values.djInstance }}
    env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: OPENDJ_JAVA_ARGS
      value: "-Xmx756m"
    volumeMounts:
    - name: dj-secrets
      mountPath: /var/run/secrets/opendj
    args: [ "pause" ]
    resources:
      requests:
        memory: 1000Mi
      limits:
        memory: 1500Mi
  volumes:
    - name: dj-secrets
      secret:
        secretName: {{ .Values.djInstance }}
{{ end }}