# For schema see https://coreos.com/operators/prometheus/docs/latest/api.html#endpoint 
# This defines a prometheus operator spec for a service to scrape.
{{- if .Values.am.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-apps: kube-prometheus
    # This label targets the prometheus operator instance
    # You could in theory have many operators running in a cluster (one for dev, qa, etc.)
    # This targets the instance that the helm chart coreos/kube-prometheus creates. 
    # Note that this ServiceMonitor needs to be in the same namespace as the operator
    # The monitored targets can be in different namespaces.
    prometheus: prometheus-operator
    app: {{ .Values.am.component }}
  name: {{ .Values.am.component }}
spec:
  # Tells prometheus which endpoint / port to scrape
  # The service definition should name the port so we can use the symbolic name below.
  endpoints:
  - port: {{ .Values.am.port }}
    path: {{ .Values.am.path }}
    basicAuth:
      password:
        name: prometheus-am
        key: password
      username:
        name: prometheus-am
        key: user
  # This targets the service using a label.
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.am.labelSelectorComponent }}
  namespaceSelector:
    {{ if eq .Values.namespaceSelectorStrategy "any" }}
    any: true
    {{ else }}
    matchNames:
      {{- range .Values.namespaceSelector }}
      - {{ . }}
      {{- end }}
    {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-am
data:
  user: {{ .Values.am.secretUser | b64enc }}
  password: {{ .Values.am.secretPassword | b64enc }}
type: Opaque
{{- end -}}