# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
# Ingress definition to configure external routes.
{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.component }}
  labels:
    app: {{ template "fullname" . }}
    vendor: forgerock
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
{{ include "tls-spec" . | indent 2 }}
  rules:
  - host: {{ template "externalFQDN" . }}
    http:
      paths:
      - path: /openam
        backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.externalPort }}
{{- end -}}
