# Copyright (c) 2016-2018 ForgeRock AS. All rights reserved
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "openam.fullname" . }}
spec:
  replicas: {{default 1 .Values.openamReplicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "openam.name" . }}
        component: {{ .Values.component }}
        vendor: forgerock
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
       {{ if eq .Values.config.strategy  "git" }}
      - name: git-init
        image: {{ .Values.gitImage.repository }}:{{ .Values.gitImage.tag }}
        imagePullPolicy: {{ .Values.gitImage.pullPolicy }}
        volumeMounts:
        - name: git
          mountPath: /git
        - name: git-secret
          mountPath: /etc/git-secret
        args: ["init"]
        envFrom:
        - configMapRef:
            name:  {{ default "frconfig" .Values.config.name  }}
      {{ end }}
      # The init containers below should be removed once file based configuration is in place.
      - name: wait-for-configstore
        image: {{ .Values.utilImage.repository }}:{{ .Values.utilImage.tag }}
        imagePullPolicy: {{ .Values.utilImage.pullPolicy }}
        args: [ "wait", "{{ .Values.configLdapHost }}", "{{ .Values.configLdapPort }}" ]
      - name: bootstrap
        image: {{ .Values.utilImage.repository }}:{{ .Values.utilImage.tag }}
        imagePullPolicy: {{ .Values.utilImage.pullPolicy }}
        env:
        - name: BASE_DN
          value: {{ .Values.rootSuffix }}
        volumeMounts:
        - name: openam-root
          mountPath: /home/forgerock/openam
        - name: openam-secrets
          mountPath: /var/run/secrets/openam
        - name: openam-boot
          mountPath: /var/run/openam
        - name: configstore-secret
          mountPath: /var/run/secrets/configstore
        args:  ["bootstrap"]
      containers:
      - name: openam
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy:  {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: openam-root
          mountPath: /home/forgerock/openam
        - name: configstore-secret
          mountPath: /var/run/secrets/configstore
        - name: openam-secrets
          mountPath: /var/run/secrets/openam/keystore
        - name: openam-pstore-secrets
          mountPath: /var/run/secrets/openam/password
        {{ if eq .Values.config.strategy  "git" }}
        - name: git
          mountPath: /git
        {{ end }}
        {{ if .Values.useConfigMapWebxml }}
        - mountPath: /usr/local/tomcat/webapps/openam/WEB-INF/web.xml
          name: webxml
          subPath: webxml
        {{ end }}
        envFrom:
        - configMapRef:
            name: am-configmap
        {{ if eq .Values.config.strategy  "git" }}
        - configMapRef:
            name:  {{ default "frconfig" .Values.config.name  }}
        {{ end }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
{{ toYaml .Values.resources | indent 10 }}
        # For slow environments like Minikube you need to give OpenAM time to come up.
        readinessProbe:
          httpGet:
            path: /isAlive.jsp
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /isAlive.jsp
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: {{ .Values.livenessTimeout }}
          periodSeconds: {{ .Values.livenessPeriod }}
      # audit logging containers
      {{- range .Values.auditLogs }}
      - name: {{ .name }}
        image: busybox
        env:
        - name: LOGFILE
          value: {{ .path }}
        args: [bin/sh, -c, 'while true; do if [ -e $LOGFILE ]; then tail -n+1 -f $LOGFILE; fi; sleep 5; done' ]
        volumeMounts:
        - name: openam-root
          mountPath: /home/forgerock/openam
      {{- end }}
      volumes:
      {{ if .Values.useConfigMapWebxml }}
      - configMap:
          defaultMode: 420
          name: webxml
        name: webxml
      {{ end }}
      - name: openam-root
        emptyDir: {}
      - name: openam-secrets
        secret:
          secretName: openam-secrets
      - name: openam-pstore-secrets
        secret:
          secretName: openam-pstore-secrets
      - name: openam-boot
        configMap:
          name: boot-json
      - name: configstore-secret
        secret:
          secretName: configstore
          #defaultMode: 256
      {{ if eq .Values.config.strategy  "git" }}
      - name: git
        emptyDir: {}
      - name: git-secret
        secret:
          secretName:  {{ default "frconfig" .Values.config.name }}
      {{ end }}
