# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
# Default values for openam-install.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value


component: amster

# Server base URL *within* the Kubernetes cluster - not the external LB URL.
# No /openam appended here.
serverBase: http://openam:80


# The top level domain (including the leading .). This excludes the openam component. 
domain: .example.com

# Install passwords.
amadminPassword: password
encryptionKey: "123456789012"
policyAgentPassword: Passw0rd


config:
  strategy: git
  # The name of the shared read write many PVC volume that holds the configuration
  name: frconfig
  # To level path where we import the the configuration from. Your git repo will usually be mounted on /git/config
  # in this pod.
  importPath: /git/config/default/am/empty-import
  # Where we perform export paths to. If not set, this defaults to the importPath
  #exportPath: /tmp/amster

image:
  repository: forgerock-docker-public.bintray.io/forgerock
  tag: 6.0.1
  pullPolicy: IfNotPresent
  #pullPolicy: Always

configStore:
  # type can be dirServer or embedded.
  type: dirServer
   # If type is set to embedded, the attributes below are ignored.
  #suffix:  "dc=openam,dc=forgerock,dc=org"
  suffix:  "o=userstore"
  # This is the first StatefulSet name:
  host: configstore-0.configstore
  port: 1389
  dirManager: "cn=Directory Manager"
  adminPort: 4444
  password: password

# This is not currently supported on install by amster. You must import a user store config.
userStore:
  host:  userstore-0.userstore
  port: 1389
  password: password
  dirManager: "cn=Directory Manager"
  suffix:  "o=userstore"

# determines if '--clean true' is used for the import-config.
# suggest this is 'true' if importing a complete configuration
# and set to 'false' if importing partial/incremental configurations
amsterClean: false

# For production set CPU limits to help Kube Schedule the pods.
resources:
 limits:
   memory: 756Mi
 requests:
   memory: 756Mi

# Optional value overrides

#  This sets the environment variable VERSION which is used by amster / commons config to
# mass update the amster version tag on import. The amster configuration contains &{version} (see forgeops-init).
# Note this is the amster version, not the version of the docker container
version: 6.0.0

# fqdn - the openam server external fqdn.
# If this is *not* set, it defaults to openam.{namespace}{{ .Values.domain }}
#fqdn: openam.acme.com

# ctsStores - is a csv separated list of avaiable cts servers. This is referenced in the amster configuration as &{ctsStores} on
# import. 
#ctsStores: ctsstore-0.ctsstore:1389

# ctsPassword - defaults to "password"
# This will be deprecated once commons secrets is integrated.
#ctsPassword: password