# Default values for frconfig.
# This is a YAML-formatted file.

# Top level domain, including the leading dot. This is used to form the wild-card cert request for cert-manager.
domain: .example.com

config:
  # The default name that products use when looking for the configmap and secret is `frconfig`.
  # To create per-product configurations, you can deploy multiple instances of this chart
  # using a different name. The corresponding product chart also need to override config.name.
  # See README.md for more information.
  name: frconfig

git:
  # git repo to clone. The value below is a public git repo that does not require authentication.
  repo: "https://github.com/ForgeRock/forgeops-init.git"
  branch: master

platform:
  idmProtectedByIg: false
  #igClientUsername: openig
  #igClientPassword: openig

# Cert manager defaults
certmanager:
  enabled: true
  # The default issuer is to use the CA certs issuer.
  issuer: ca-issuer
  # And a local to namespace issuer
  issuerKind: Issuer
  # For lets encrypt use this:
  #acme: true
  #issuer: letsencrypt-prod
  #issuerKind: ClusterIssuer
