namespace: default
resources:
  - ../../../base/kustomizeConfig
  - ../../../base/forgeops-secrets
  - ../../../base/7.0/ds/cts
  - ../../../base/7.0/ds/idrepo
  - ../../../base/am
  - ../../../base/amster
  - ../../../base/idm
  - ../../../base/end-user-ui
  - ../../../base/web
  - ../../../base/7.0/ingress
  - storage.yaml
  - sa.yaml
  - scc.yaml

secretGenerator:
- name: platform-secrets
  literals:
  # Password used at installation time.
  # Change after installation.
  - ADMIN_PASSWORD=password

patchesStrategicMerge:
- am.yaml
- idm.yaml
- web.yaml
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: platform-config
  data:
    SUBDOMAIN: "apps"
    DOMAIN: "fropenshift.openshift.forgeops.com"
- |-
  #Patch DS CTS
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: ds-cts
  spec:
    replicas: 3
    template:
      spec:
        containers:
          - name: ds
            resources:
              requests:
                memory: 11Gi
                cpu: 8000m
              limits:
                memory: 14Gi
    volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          pv.beta.kubernetes.io/gid: "0"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 850Gi
        storageClassName: fast

- |-
  #Patch DS idrepo
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: ds-idrepo
  spec:
    replicas: 3
    template:
      spec:
        containers:
          - name: ds
            resources:
              requests:
                memory: 8Gi
                cpu: 4000m
              limits:
                memory: 11Gi
    volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          pv.beta.kubernetes.io/gid: "0"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 512Gi
        storageClassName: fast

patches:
- path: ds.yaml
  target:
    kind: StatefulSet
    name: ds