# Default values for apache-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

component: apache-agent

global:
  domain: .example.com
  image:
    repository: forgerock
    tag: 5.5.0
    pullPolicy: IfNotPresent
  # If you set this to true, you must have a TLS secret with the same name as the FQDN.
  useTLS: false


service:
  name: apache
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources: {}
#  limits:
#    cpu: 100m
#    memory: 256Mi
#  requests:
#    cpu: 100m
#    memory: 256Mi

