commonLabels:
  app.kubernetes.io/name: ds
  app.kubernetes.io/instance: ds-cts
  app.kubernetes.io/component: directory
  app.kubernetes.io/part-of: forgerock
resources:
- ds-cts.yaml

images:
- name: ds-cts
  newName: gcr.io/forgeops-public/ds-cts
  newTag: 7.1.0

configurations:
- kustomizeConfig.yaml