commonLabels:
  app.kubernetes.io/name: ds
  app.kubernetes.io/instance: ds-cts
  app.kubernetes.io/component: directory
  app.kubernetes.io/part-of: forgerock
resources:
- ds-cts.yaml

images:
- name: ds-cts
  newName: us-docker.pkg.dev/forgeops-public/images/ds-cts
  newTag: 7.1.2

configurations:
- kustomizeConfig.yaml