namespace: tekton-pipelines

resources:
- amster-load.yaml
- build-images-task.yaml
- deploy-base-ds.yaml
- deploy-images-task.yaml
- notify-task.yaml
- nuke-deployment.yaml
- skaffold-deploy-apps.yaml
- skaffold-run.yaml
- slack-notify.yaml
- wait-platform-up.yaml
- smoke-test-task.yaml

configMapGenerator:
- name: tekton-scripts
  files:
  - scripts/run-smoke-test.sh

generatorOptions:
  disableNameSuffixHash: true