apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "smoketest.fullname" . }}
  labels:
    app: {{ include "smoketest.name" . }}
    chart: {{ include "smoketest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "smoketest.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "smoketest.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: toolbox-{{ .Release.Namespace }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["smoke-tests"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          - name: GIT_REPO
            value: "https://github.com/ForgeRock/forgeops-init.git"
          - name: GIT_BRANCH
            value: master
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
          resources:
{{ toYaml .Values.resources | indent 12 }}
        - name: web 
          image: nginx:latest 
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        emptyDir: {}

