image:
  #repository: forgerock-docker-public.bintray.io/ds
  repository: gcr.io/engineering-devops/ds
  tag: 6.5.0-M129.2-CTS-TTL
  pullPolicy: Always

instance: ctsstore

userstore:
  enabled: false

resources:
  limits:
    memory: 14Gi
    cpu: 10000m
  requests:
    memory: 10Gi
    cpu: 8000m

storageSize: 850Gi
storageClass: fast

# For JDK 8
opendjJavaArgs: >  
  -server -Xms10g -Xmx10g -XX:+UseG1GC -XX:+UseNUMA -XX:+UseCompressedOops
  -XX:MaxGCPauseMillis=200 -XX:G1MixedGCCountTarget=12 -XX:MetaspaceSize=256m  
  -XX:ConcGCThreads=5 -XX:+PrintGCApplicationStoppedTime
  -XX:+ParallelRefProcEnabled -XX:InitiatingHeapOccupancyPercent=70
  -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintGCDetails
  -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -XX:+PrintTenuringDistribution 
  -Xloggc:/tmp/gc.log

#-server -Xms11g -Xmx11g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA 
#-XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps 
#-XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log
   
# For JDK 11
#opendjJavaArgs: >
# -server -Xms10g -Xmx10g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA  
# -XX:MaxGCPauseMillis=100 -verbose:gc -Xlog:gc:/tmp/gc.log

podAntiAffinity: hard

runPostSetupJob: false

replicas: 2

topologyKey: "failure-domain.beta.kubernetes.io/zone"
