apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: openam-hpa
  #namespace: prod
  labels:
    app: openam
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: openam-prod-openam
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
