image:
  #repository: forgerock-docker-public.bintray.io/openidm
  repository: gcr.io/engineering-devops/openidm
  tag: 6.5.0-M5
  pullPolicy: Always
  
resources:
  limits:
    cpu: 10000m
    memory: 6Gi
  requests:
    cpu: 2000m
    memory: 4Gi

# For JDK 8
javaOpts: >
  -server -Xms4g -Xmx4g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA 
  -XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps 
  -XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log
#  -Dcom.sun.management.jmxremote
#  -Dcom.sun.management.jmxremote.port=9010
#  -Dcom.sun.management.jmxremote.local.only=false
#  -Dcom.sun.management.jmxremote.authenticate=false
#  -Dcom.sun.management.jmxremote.ssl=false
#  -Djava.rmi.server.hostname=localhost
#  -Dcom.sun.management.jmxremote.rmi.port=9010

replicaCount: 1

config:
  name: frconfig
  #path: /git/config/6.5/m-cluster/idm/ds-repo-explicit
  path: /git/config/6.5/default/idm/sync-with-ldap-bidirectional
  strategy: git

openidm:
  repo:
    host: postgresql
    port: 5432
    user: openidm
    password: openidm
    schema: openidm
    databaseName: openidm
    # DS external repo
    #host: userstore-0.userstore
    #port: 1389
    #user: "cn=Directory Manager"
    #password: password