image:
  repository: gcr.io/engineering-devops/openam
  #tag: 6.1.0
  #repository: forgerock-docker-public.bintray.io/openam
  tag: 6.5.0-M9
  pullPolicy: Always
  
resources:
  limits:
    memory: 11Gi
    cpu: 12000m
  requests:
    memory: 8Gi
    cpu: 8000m

# Use these for JDK8
catalinaOpts: >
  -server -Xms8g -Xmx8g -XX:+UseG1GC -XX:+UseNUMA -XX:+UseCompressedOops
  -XX:MaxGCPauseMillis=200 -XX:G1MixedGCCountTarget=12 -XX:MetaspaceSize=256m  
  -XX:ConcGCThreads=5 -XX:+PrintGCApplicationStoppedTime -XX:+PrintFlagsFinal
  -XX:+ParallelRefProcEnabled -XX:InitiatingHeapOccupancyPercent=70
  -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true
  -Dcom.sun.identity.util.debug.provider=com.sun.identity.shared.debug.impl.StdOutDebugProvider
  -Dcom.sun.identity.shared.debug.file.format='%PREFIX% %MSG%\\n%STACKTRACE%'
  -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintGCDetails
  -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -XX:+PrintTenuringDistribution 
  -Xloggc:/tmp/gc.log

# -XX:+PrintGCApplicationConcurrentTime -XX:ParallelGCThreads=12 -XX:+UseStringDeduplication -XX:G1HeapWastePercent=4

# Use these for JDK11
#catalinaOpts: >
#  -Xms7g -Xmx7g -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -Xlog:gc*:/tmp/gc.log
#  -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true
#  -Dcom.sun.identity.util.debug.provider=com.sun.identity.shared.debug.impl.StdOutDebugProvider
#  -Dcom.sun.identity.shared.debug.file.format='%PREFIX% %MSG%\\n%STACKTRACE%'


