djInstance: userstore

numberSampleUsers: "1000"

resources:
  limits:
    memory: 11Gi
  requests:
    memory: 8Gi

opendjJavaArgs: >
  -server -Xms8g -Xmx8g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA 
  -XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps 
  -XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log

storageSize: "500Gi"
storageClass: "fast"

replicas: 2

topologyKey: "failure-domain.beta.kubernetes.io/zone"