apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-users
spec:
  params:
  - name: users
    type: string
    description: number of users to create
    
  - name: profile
    type: string
    description: profile
  stepTemplate:
    env:
    - name: SLACK_FAILED_WEBHOOK_URL
      valueFrom:
        secretKeyRef:
          name: "slack-webhook-$(params.profile)"
          key: SLACK_FAILED_WEBHOOK_URL
  steps:
    - name: wait-for-all-pods-ready
      image: gcr.io/cloud-builders/kubectl
      script: |
        #!/usr/bin/env bash
        {
          sleep 15
          kubectl -n $(params.profile) wait --for=condition=complete --timeout=120s job -l app=forgeops-secrets --all
          kubectl -n $(params.profile) wait --for=condition=ready --timeout=600s pod -l vendor=forgerock --all
        } || {
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Some pods still unhealthy after 600s. Failed to create users"}' $SLACK_FAILED_WEBHOOK_URL
          exit 1
        }

    - name: wait-for-amster-config
      image: gcr.io/cloud-builders/kubectl
      script: |
        #!/usr/bin/env bash
        {
          # Obtain the amster pod name, tail the logs until the string is found      
          (kubectl -n $(params.profile) logs $(kubectl -n $(params.profile) get pod -l app=amster -o jsonpath="{.items[0].metadata.name}") -f &) | grep -qi "configuration script finished"
        } || {
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Amster config failed"}' $SLACK_FAILED_WEBHOOK_URL
          exit 1
        }
      
    - name: create-users
      image: gcr.io/cloud-builders/kubectl
      script: |
        #!/usr/bin/env bash
        {
          #set ADMIN_PASSWORD and run make-users.sh 
          
          ADMIN_PASSWORD=$(kubectl -n $(params.profile) get secret ds-passwords -o jsonpath="{.data.dirmanager\.pw}" | base64 --decode)
          kubectl -n $(params.profile) exec ds-idrepo-0 -- bash -c "ADMIN_PASSWORD=$ADMIN_PASSWORD make-users.sh $(inputs.params.users)"
        } || {
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Failed to create users. See pipeline logs"}' $SLACK_FAILED_WEBHOOK_URL
          exit 1
        }      
    
