apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: notify
spec:
  params:
  - name: namespace
    type: string
    description: target namespace
  steps:
    - name: notify-send-passwords
      image: gcr.io/cloud-builders/kubectl
      env:
      - name: SLACK_WEBHOOK_URL
        valueFrom:
          secretKeyRef:
            name: "slack-webhook-$(params.namespace)"
            key: SLACK_WEBHOOK_URL
      script: |
        #!/usr/bin/env bash
        getsec () {
        kubectl -n $(params.namespace) get secret $1 -o jsonpath="{.data.$2}" | base64 --decode
        }
        OUT=./temp.json
        cat <<EOF >$OUT
        {
          "blocks": [{
            "type": "section",
            "text": {
              "text": "$(params.namespace) pipeline Successful. Random Passwords generated for $(params.namespace)'s environment. See:\n<https://$(params.namespace).iam.forgeops.com/admin>\n<https://$(params.namespace).iam.forgeops.com/am>\n<https://$(params.namespace).iam.forgeops.com/enduser>",
              "type": "mrkdwn"
            },
            "fields": [
              {
                "type": "mrkdwn",
                "text": "*uid=admin*: \`$(getsec ds-passwords dirmanager\\.pw)\`"
              },
              {				
                "type": "mrkdwn",
                "text": "*amadmin*: \`$(getsec amster-env-secrets AMADMIN_PASS)\`"
              },
              {	
                "type": "mrkdwn",
                "text": "*openidm-admin*: \`$(getsec idm-env-secrets OPENIDM_ADMIN_PASSWORD)\`"
              },
            ]
          }]
        }
        EOF
        cat $OUT
        curl -X POST -H 'Content-type: application/json' --data @temp.json $SLACK_WEBHOOK_URL


