apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: scale-am-deployment
spec:
  inputs:
    params:
      - name: replicas
        type: string
        description: number of users to create
  stepTemplate:
    env:
    - name: SLACK_FAILED_WEBHOOK_URL
      valueFrom:
        secretKeyRef:
          name: slack-webhook
          key: SLACK_FAILED_WEBHOOK_URL
  steps:
    - name: scale-am-tozero
      image: gcr.io/cloud-builders/kubectl
      script: |
        #!/usr/bin/env bash
        {
          kubectl scale deployment am --replicas=0
        } || {
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Failed to scale AM to zero. See pipeline logs"}' $SLACK_FAILED_WEBHOOK_URL
          exit 1
        }

    - name: wait-10-seconds
      image: gcr.io/cloud-builders/kubectl
      command: ["bash", "-c"]
      args: ["sleep 10; echo 'done' "]
      
    - name: scale-am-todesired
      image: gcr.io/cloud-builders/kubectl
      script: |
        #!/usr/bin/env bash
        {
          kubectl scale deployment am --replicas=$(inputs.params.replicas)
        } || {
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Failed to scale AM back to $(inputs.params.replicas). See pipeline logs"}' $SLACK_FAILED_WEBHOOK_URL
          exit 1
        }

    - name: wait-for-all-pods-ready
      image: gcr.io/cloud-builders/kubectl
      script: |
        #!/usr/bin/env bash
        {
          sleep 15
          kubectl wait --for=condition=ready --timeout=600s pod -l vendor=forgerock --all
        } || {
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Some pods are not healthy after AM restart. See pipeline logs"}' $SLACK_FAILED_WEBHOOK_URL
          exit 1
        }
    
