# This is a dummy secret. If you need an ssh access for cloning replace this with a real id_rsa secret.
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.config.name }}
    annotations:
      "helm.sh/resource-policy": keep
type: Opaque
data:
  id_rsa:
    {{ b64enc "This_is_a_dummy_key_for_git_repo_cloning" }}