# ForgeOps gatling helm chart
# This is a YAML-formatted file.

# Domain on which reports will be available
domain: .forgeops.com

# Gatling image with tests.
# Dockerfile for this image can be found in forgeops/docker/gatling
image:
  repository: gcr.io/engineering-devops/gatling:6.5.0
  pullPolicy: Always

# Resources for gatling benchmark chart
resources:
  limits:
    memory: 4096Mi
  requests:
    memory: 2048Mi

# Gatling heap
# Heap should be always max 75% of resource.limits.memory settings
javaopts: -Xmx2G

benchmark:
  # Name of scala test name to run
  # This benchmark supports following testnames
  #   - am.AMRestAuthNSim
  #   - am.AMAccessTokenSim
  #
  # For IDM it is:
  # ( Always run Create test first to have users present for other tests)
  # - idm.IDMCreateManagedUsers
  # - idm.IDMReadManagedUsers
  # - idm.IDMUpdateManagedUsers
  # - idm.IDMDeleteManagedUsers
  #

  testname: am.AMAccessTokenSim

  # How many users we want to use for benchmark
  users: "1000"
  # How many user threads we want to use for benchmark
  concurrency: 50
  # Duration of test in seconds
  duration: 60
  # Logout percent in authn testnames(0 disables logout)
  logoutpercent: 0
  # Warmup duration
  warmup: 1
  # Token info - enables getting tokeninfo in AMAccessTokenSim tests
  get_token_info: "false"

  # Product specific values that are passed into gatling.
  # Will likely to exapand in future to cover all 4 products.
  # In case you are running gatling in different namespace
  # you need to specify host as a full fqdn. e.g openam.pyforge.forgeops.com
  openam:
    host: openam
    port: 80
  openidm:
    host: openidm
    port: 80

# Reporting related values.
component: gatling
service:
  name: forgeops-benchmark
  type: ClusterIP
  externalPort: 80
  internalPort: 80
ingress:
  class: nginx
