# Default values for dsadmin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

component: ds

image:
  repository: forgerock-docker-public.bintray.io/forgerock/ds
  pullPolicy: IfNotPresent
  tag: 6.5.0-M129.2

gcs:
  enabled: false
  # GCS Bucket destination. You need the right scopes in container engine to write to this bucket.
  #add --scopes storage-full when you create the cluster.
  bucket:  gs://forgeops/ds-backups

s3:
  enabled: true
  # S3 Bucket destination
  bucket: s3://forgeops/dj-backup
  
storage: {}

# If the pvc / pv already exists, use --set backup.createPVC=false
createPVC: true

backup:
  # The name of the PVC to create to hold backups from all ds instances.
  pvcName: ds-backup
  # The size of the resource request to the PV
  storageSize: "20Gi"
  # Do not uncomment.  Place holder for future work
  # verify: false
  
# For creating the PV, we need to speficy the server and the path to the export
nfs:
  server: 10.191.193.66
  path: /export

# An optional slack webhook url. It can be used by the backup and verification processes to post notifications to slack.
# If you don't have slack, set this to "undefined"
slackUrl: undefined