# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
# Secrets for OpenAM stack deployment.
# Note that secret vals are base64-encoded.
# The base64-encoded value of 'password' is 'cGFzc3dvcmQ='.
# Watch for trailing \n when you encode!
apiVersion: v1
kind: Secret
metadata:
    name: amster-secrets
type: Opaque
data:
{{ (.Files.Glob "secrets/*").AsSecrets| indent 2 }}
