# Deploys the "large" size to prod.iam.example.com. Uses the Let's encrypt issuer for SSL.
namespace: prod
resources:
- ../../../base/kustomizeConfig
- ../../../base/forgeops-secrets
- ../../../base/postgres
- ../../../base/6.5/ds/cts
- ../../../base/6.5/ds/idrepo
- ../../../base/am
- ../../../base/amster
- ../../../base/idm
- ../../../base/6.5/ingress

configMapGenerator:
- name: platform-config
  # The env vars below can be passed into a pod using the envFrom pod spec.
  # These global variables can be used to parameterize your deployments.
  # The FQDN and URLs here should match your ingress or istio gateway definitions
  literals:
  - FQDN=$(NAMESPACE).iam.example.com
  - SUBDOMAIN=iam
  - DOMAIN=example.com
  - AM_URL=https://$(NAMESPACE).iam.example.com/am
  - IDM_ADMIN_URL=https://$(NAMESPACE).iam.example.com/admin
  - PLATFORM_ADMIN_URL=https://$(NAMESPACE).iam.example.com/platform
  - IDM_REST_URL=https://$(NAMESPACE).iam.example.com/openidm
  - LOGIN_UI_URL=https://$(NAMESPACE).iam.example.com/login/#/service/Login
  - THEME=default
  - CTS_STORES=ds-cts-0.ds-cts:1389,ds-cts-1.ds-cts:1389,ds-cts-2.ds-cts:1389

# The variables defined below can be referenced in resources using the syntax $(VARIABLE)
vars:
- name: DOMAIN
  fieldref:
    fieldpath: data.DOMAIN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: platform-config
- name: SUBDOMAIN
  fieldref:
    fieldpath: data.SUBDOMAIN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: platform-config
- name: NAMESPACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: platform-config
  fieldref:
    fieldpath: metadata.namespace

patchesStrategicMerge:
- |-
  #Patch AM
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: am
  spec:
    replicas: 1
    template:
      spec:
        containers:
        - name: openam
          imagePullPolicy: Always
          resources:
            limits:
              memory: 24Gi
            requests:
              cpu: 10000m
              memory: 23Gi
- |-
  #Patch IDM
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: idm
  spec:
    replicas: 2
    template:
      spec:
        containers:
        - name: openidm
          imagePullPolicy: Always
          resources:
            limits:
              memory: 6Gi
            requests:
              cpu: 4000m
              memory: 6Gi

- |-
  #Patch DS CTS
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: ds-cts
  spec:
    replicas: 3
    template:
      spec:
        containers:
          - name: ds
            resources:
              requests:
                memory: 14Gi
                cpu: 10000m
              limits:
                memory: 16Gi
            env:
            - name: DS_SET_SIZE
              value: "3"
        nodeSelector:
          forgerock.io/role: ds
    volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          pv.beta.kubernetes.io/gid: "0"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 850Gi
        storageClassName: fast
    - metadata:
        name: backup
        annotations:
          pv.beta.kubernetes.io/gid: "0"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500Gi


- |-
  #Patch DS idrepo
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: ds-idrepo
  spec:
    replicas: 3
    template:
      spec:
        containers:
        - name: ds
          resources:
            requests:
              memory: 14Gi
              cpu: 10000m
            limits:
              memory: 16Gi
          env:
          - name: DS_SET_SIZE
            value: "3"
        nodeSelector:
          forgerock.io/role: ds
    volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          pv.beta.kubernetes.io/gid: "0"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1024Gi
        storageClassName: fast
    - metadata:
        name: backup
        annotations:
          pv.beta.kubernetes.io/gid: "0"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500Gi

- |-
  #Patch postgres
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: postgres-idm
  spec:
    replicas: 1
    template:
      spec:
        containers:
        - name: postgres
          resources:
            limits:
              memory: 6Gi
            requests:
              cpu: 6000m
              memory: 5Gi
    volumeClaimTemplates:
      - metadata:
          name: postgres-idm
        spec:
          storageClassName: fast
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 200Gi