image:
  repository: forgerock-docker-public.bintray.io/forgerock/amster
  tag: 6.5.0
  pullPolicy: IfNotPresent

config:
  importPath: /git/config/6.5/cdm/m-cluster/am
  #importPath: /git/config/6.5/default/am/empty-import
  exportPath: /tmp/amster

amadminPassword: password

ctsStores: ctsstore-0.ctsstore:1389,ctsstore-1.ctsstore:1389
ctsPassword: password

# For production set CPU limits to help Kube Schedule the pods.
resources:
 limits:
   memory: 756Mi
 requests:
   memory: 756Mi