image:
  #repository: gcr.io/engineering-devops/openam
  repository: forgerock-docker-public.bintray.io/forgerock/openam
  tag: 6.5.0
  pullPolicy: IfNotPresent
  
resources:
  limits:
    memory: 26Gi
    cpu: 16000m
  requests:
    memory: 20Gi
    cpu: 10000m

# Use these for JDK8
catalinaOpts: >
  -server -Xms20g -Xmx20g -XX:+UseG1GC -XX:+UseNUMA -XX:+UseCompressedOops
  -XX:MaxGCPauseMillis=200 -XX:G1MixedGCCountTarget=12 -XX:MetaspaceSize=128m
  -XX:ConcGCThreads=5 -XX:+CMSScavengeBeforeRemark -XX:InitiatingHeapOccupancyPercent=70
  -XX:+PrintGCApplicationStoppedTime -XX:+PrintFlagsFinal -XX:+ParallelRefProcEnabled
  -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true
  -Dcom.sun.identity.util.debug.provider=com.sun.identity.shared.debug.impl.StdOutDebugProvider
  -Dcom.sun.identity.shared.debug.file.format='%PREFIX% %MSG%\\n%STACKTRACE%'
  -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintGCDetails
  -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -XX:+PrintTenuringDistribution 
  -Xloggc:/tmp/gc.log

# -XX:+PrintGCApplicationConcurrentTime -XX:ParallelGCThreads=12 -XX:+UseStringDeduplication 
# -XX:G1HeapWastePercent=4 -XX:NewRatio -XX:MaxTenuringThreshold=1

# Use these for JDK11
#catalinaOpts: >
#  -Xms7g -Xmx7g -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -Xlog:gc*:/tmp/gc.log
#  -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true
#  -Dcom.sun.identity.util.debug.provider=com.sun.identity.shared.debug.impl.StdOutDebugProvider
#  -Dcom.sun.identity.shared.debug.file.format='%PREFIX% %MSG%\\n%STACKTRACE%'


