kind: ""
apiversion: ""
commonLabels:
  app.kubernetes.io/name: ldif-importer
  app.kubernetes.io/instance: ldif-importer
  app.kubernetes.io/component: directory
  app.kubernetes.io/part-of: forgerock
  app: ldif-importer
resources:
- job.yaml