# Copyright (c) 2016-2018 ForgeRock AS. All rights reserved.
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    component: {{ .Values.component }}
    vendor: forgerock
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: idm
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        component: {{ .Values.component }}
        vendor: forgerock
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      {{ if eq .Values.config.strategy  "git" }}
      initContainers:
      - name: git-init
        image: {{ .Values.gitImage.repository }}:{{ .Values.gitImage.tag }}
        imagePullPolicy: {{ .Values.gitImage.pullPolicy }}
        volumeMounts:
        - name: git
          mountPath: /git
        - name: git-secret
          mountPath: /etc/git-secret
        args: ["init"]
        envFrom:
        - configMapRef:
            name:  {{ default "frconfig" .Values.config.name  }}
        {{ if .Values.sedFilter }}
        env:
        - name: SED_FILTER
          value: {{ .Values.sedFilter }}
        {{ end }}
      {{ end }}
      containers:
      - name: openidm
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ template "fullname" . }}
        - configMapRef:
            name:  {{ default "frconfig" .Values.config.name  }}
        - secretRef:
            name: {{ default "frconfig" .Values.config.name }}-platform
        - secretRef:
            name: {{ default "openidm-secrets-env" .Values.secret.name  }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /openidm/info/ping
            port: 8080
            httpHeaders:
            - name: X-OpenIDM-Username
              value: anonymous
            - name: X-OpenIDM-Password
              value: anonymous
            - name: X-OpenIDM-NoSession
              value:  "true"
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 30
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - name: openidm-secrets
          mountPath: /opt/openidm/secrets
        - name: logs
          mountPath: /opt/openidm/logs
        - name: audit-logs
          mountPath: /opt/openidm/audit
        {{ if eq .Values.config.strategy  "git" }}
        - name: git
          mountPath: /git
        {{ end }}
        - name: boot-properties
          mountPath: /var/run/openidm/commons
        - name: logging-properties
          mountPath: /var/run/openidm/logging
      {{ if eq .Values.config.strategy  "git" }}
      - name: git
        image: {{ .Values.gitImage.repository }}:{{ .Values.gitImage.tag }}
        imagePullPolicy: {{ .Values.gitImage.pullPolicy }}
        volumeMounts:
        - name: git
          mountPath: /git
        - name: git-secret
          mountPath: /etc/git-secret
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args: [ "pause"]
      {{ end }}
      # audit logging containers
      {{- range .Values.auditLogs }}
      - name: {{ .name }}
        image: busybox
        env:
        - name: LOGFILE
          value: {{ .path }}
        args: [bin/sh, -c, 'while true; do if [ -e $LOGFILE ]; then tail -n+1 -f $LOGFILE; fi; sleep 5; done' ]
        volumeMounts:
        - name: audit-logs
          mountPath: /opt/openidm/audit
      {{- end }}
      volumes:
      - name: openidm-secrets
        secret:
          secretName: openidm-secrets
      - name: logs
        emptyDir: {}
      - name: audit-logs
        emptyDir: {}
      - name: boot-properties
        configMap:
          name: idm-boot-properties
      - name: logging-properties
        configMap:
          name: idm-logging-properties
      {{- if eq .Values.config.strategy "git" }}
      - name: git
        emptyDir:  {}
      - name: git-secret
        secret:
          secretName:  {{ default "frconfig" .Values.config.name }}
      {{ end }}
