# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
# Secrets for OpenIDM stack deployment.
# Note that secret values are base64-encoded.
apiVersion: v1
kind: Secret
metadata:
   name: "openidm-secrets-env"
type: Opaque
data:
   OPENIDM_ADMIN_PASSWORD: {{ default "openidm-admin" .Values.secret.openidmAdminPassword | b64enc }}
