apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: utils-pipeline-trigger
  annotations:
    cert-manager.io/cluster-issuer: "default-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/utils)$ $1/ redirect;
spec:
  rules:
  - host: tekton-pipelines.iam.forgeops.com
    http:
      paths:
      - backend:
          serviceName: el-utils-listener
          servicePort: 8080
        path: /utils/?(.*)
  tls:
  - hosts:
    - tekton-pipelines.iam.forgeops.com
    secretName: sslcert
