{{- if .Values.ds_idrepo.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds-idrepo
  labels:
    {{- include "identity-platform.labels" . | nindent 4 }}
    {{- with .Values.ds_idrepo.podLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.ds_idrepo.replicaCount }}
  selector:
    matchLabels:
      {{- include "identity-platform.selectorLabels" . | nindent 6 }}
      {{- with .Values.ds_idrepo.podLabels }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
  serviceName: ds-idrepo
  template:
    metadata:
      annotations:
        deployment-date: {{ now | quote }}
        {{- with .Values.ds_idrepo.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "identity-platform.selectorLabels" . | nindent 8 }}
        {{- with .Values.ds_idrepo.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.ds_idrepo.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.ds_idrepo.image.imagePullSecrets | nindent 8 }}
      {{- else if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "identity-platform.serviceAccountName" . }}
      subdomain: ds-idrepo
      securityContext:
        {{- toYaml .Values.ds_idrepo.podSecurityContext | nindent 8 }}
      volumes:
        - name: ds-master-keypair
          secret:
            secretName: ds-master-keypair
        - name: ds-ssl-keypair
          secret:
            secretName: ds-ssl-keypair
        - name: truststore
          secret:
            secretName: ds-ssl-keypair
        - name: admin-password
          secret:
            secretName: ds-passwords
        - name: monitor-password
          secret:
            secretName: ds-passwords
        - name: keys
          emptyDir: {}
        - name: cloud-credentials-cache
          emptyDir: {}
        {{- if .Values.ds_idrepo.lifecycleScripts.enabled }}
        - name: lifecycle-scripts
          configMap:
            name: ds-idrepo-lifecycle-scripts
            defaultMode: 0755
        {{- end }}
      initContainers:
        - name: init
          securityContext:
            {{- toYaml .Values.ds_idrepo.securityContext | nindent 12 }}
          image: "{{ .Values.ds_idrepo.image.repository }}:{{ .Values.ds_idrepo.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ds_idrepo.image.pullPolicy }}
          volumeMounts:
          {{- if .Values.ds_idrepo.volumeClaimSpec }}
          - mountPath: /opt/opendj/data
            name: data
          {{- end }}
          - mountPath: /var/run/secrets/admin
            name: admin-password
          - mountPath: /var/run/secrets/monitor
            name: monitor-password
          - mountPath: /var/run/secrets/ds-ssl-keypair
            name: ds-ssl-keypair
          - mountPath: /var/run/secrets/ds-master-keypair
            name: ds-master-keypair
          - mountPath: /var/run/secrets/truststore
            name: truststore
          - mountPath: /var/run/secrets/keys
            name: keys
          - mountPath: /var/run/secrets/cloud-credentials-cache/
            name: cloud-credentials-cache
          {{- if .Values.ds_idrepo.lifecycleScripts.enabled }}
          - mountPath: /opt/opendj/scripts
            name: lifecycle-scripts
          {{- end }}
          # args:
          # - init
          command: ["/opt/opendj/default-scripts/init-and-restore.sh"]
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: DS_SET_UID_ADMIN_AND_MONITOR_PASSWORDS
            value: "true"
          - name: DS_UID_MONITOR_PASSWORD_FILE
            value: /var/run/secrets/monitor/monitor.pw
          - name: DS_UID_ADMIN_PASSWORD_FILE
            value: /var/run/secrets/admin/dirmanager.pw
          - name: DSBACKUP_HOSTS
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: DSBACKUP_HOSTS
          - name: DSBACKUP_DIRECTORY
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: DSBACKUP_DIRECTORY
          - name: AUTORESTORE_FROM_DSBACKUP
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: AUTORESTORE_FROM_DSBACKUP
          - name: DISASTER_RECOVERY_ID
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: DISASTER_RECOVERY_ID
          envFrom:
          - secretRef:
              name: cloud-storage-credentials
              optional: true
      containers:
        - name: ds
          securityContext:
            {{- toYaml .Values.ds_idrepo.securityContext | nindent 12 }}
          image: "{{ .Values.ds_idrepo.image.repository }}:{{ .Values.ds_idrepo.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ds_idrepo.image.pullPolicy }}
          args:
          - start-ds
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: DS_SET_UID_ADMIN_AND_MONITOR_PASSWORDS
            value: "true"
          - name: DS_UID_MONITOR_PASSWORD_FILE
            value: /var/run/secrets/monitor/monitor.pw
          - name: DS_UID_ADMIN_PASSWORD_FILE
            value: /var/run/secrets/admin/dirmanager.pw
          envFrom:
          - secretRef:
              name: cloud-storage-credentials
              optional: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: tcp-ldap
              containerPort: 1389
              protocol: TCP
            - name: tcp-ldaps
              containerPort: 1636
              protocol: TCP
            - name: tcp-admin
              containerPort: 4444
              protocol: TCP
            - name: tcp-replication
              containerPort: 8989
              protocol: TCP
          startupProbe:
            httpGet:
              path: /healthy
              port: http
            {{- with .Values.ds_idrepo.startupProbe }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.ds_idrepo.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.ds_idrepo.volumeClaimSpec }}
          - mountPath: /opt/opendj/data
            name: data
          {{- end }}
          - mountPath: /var/run/secrets/admin
            name: admin-password
          - mountPath: /var/run/secrets/monitor
            name: monitor-password
          - mountPath: /var/run/secrets/ds-ssl-keypair
            name: ds-ssl-keypair
          - mountPath: /var/run/secrets/ds-master-keypair
            name: ds-master-keypair
          - mountPath: /var/run/secrets/truststore
            name: truststore
          - mountPath: /var/run/secrets/keys
            name: keys
          - mountPath: /var/run/secrets/cloud-credentials-cache/
            name: cloud-credentials-cache
          {{- if .Values.ds_idrepo.lifecycleScripts.enabled }}
          - mountPath: /opt/opendj/scripts
            name: lifecycle-scripts
          {{- end }}
      {{- with .Values.ds_idrepo.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ds_idrepo.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      {{- if .Values.ds_idrepo.tolerations }}
        {{- toYaml .Values.ds_idrepo.tolerations | nindent 8 }}
      {{- else if .Values.platform.tolerations }}
        {{- toYaml .Values.platform.tolerations | nindent 8 }}
      {{- end }}
  {{- if .Values.ds_idrepo.volumeClaimSpec }}
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        pv.beta.kubernetes.io/gid: "0"
      labels:
        {{- include "identity-platform.labels" . | nindent 8 }}
        {{- with .Values.ds_idrepo.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- toYaml .Values.ds_idrepo.volumeClaimSpec | nindent 6 }}
  {{- end }}
{{- end }}
