resources:
  - ../../../base/amster

images:
- name: amster
  newName: gcr.io/forgeops-public/amster
  newTag: 7.1.0

# Remove the amster initContainer as that is only required for import/export jobs
patchesJSON6902:
- target:
    group: batch
    version: v1
    kind: Job
    name: amster
  patch: |-
    - op: remove
      path: /spec/template/spec/initContainers/0

patchesStrategicMerge:
- |-
  apiVersion: batch/v1
  kind: Job
  metadata:
    name: amster
  spec:
    backoffLimit: 0
    template:
      spec:
        containers:
        - name: pause
          command: ["/bin/sh", "-c"]
          args:
          - |
            cp /amster-scripts/* /opt/amster/
            ./docker-entrypoint.sh pause