# am-only profile used for PIT tests
namespace: default
resources:
  - ../../../base/kustomizeConfig
  - ../../../base/forgeops-secrets
  - ../../../base/am-cdk
  - ../../../base/amster
  - ../../../base/7.0/ds/cts
  - ../../../base/7.0/ds/idrepo
  - ../../../base/7.0/ingress
  - ../../../base/ldif-importer
  - ../../../base/end-user-ui
  - ../../../base/login-ui
  - ../../../base/admin-ui

