resources:
- ../base
nameSuffix: -cts
images:
- name: ds
  newName: ds-cts
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: ds-cts
    app.kubernetes.io/component: directory
    app.kubernetes.io/instance: ds-cts
    app.kubernetes.io/name: ds
    app.kubernetes.io/part-of: forgerock
