# Default values for end-user-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Top level domain. Used to create the ingress
domain: .example.com

# These are both used to form the FQDN for the load balancer.  See _helpers.tpl
component: end-user-ui

image:
  repository: gcr.io/forgerock-io/end-user-ui
  tag: 6.5.2
  pullPolicy: IfNotPresent

service:
  name: end-user-ui
  type: ClusterIP
  externalPort: 80
  internalPort: 8888


ingress:
  enabled: true
  annotations: {}
