kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/component: ui
  app.kubernetes.io/instance: end-user-ui
  app.kubernetes.io/name: end-user-ui
  app.kubernetes.io/part-of: forgerock
  tier: ui
resources:
- deployment.yaml
- service.yaml
images:
- name: .*end-user-ui.*
  newName: gcr.io/forgerock-io/platform-enduser-ui
  newTag: 7.3.1
