kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- deployment.yaml
- service.yaml
images:
- name: .*enduser-ui.*
  newName: gcr.io/forgerock-io/platform-enduser-ui
  newTag: 7.5.0
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: ui
    app.kubernetes.io/instance: end-user-ui
    app.kubernetes.io/name: end-user-ui
    app.kubernetes.io/part-of: forgerock
    tier: ui
