# Copyright (c) 2016-2018 ForgeRock AS.
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Values.djInstance }}
  labels:
    djInstance: {{ .Values.djInstance }}
    app: {{ template "fullname" . }}
    vendor: forgerock
    component: {{ .Values.component }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ .Values.djInstance }}
  replicas: {{default 1 .Values.replicas }}
  {{- if .Values.djPersistence }}
  volumeClaimTemplates:
  - metadata:
      name: db
      annotations:
        pv.beta.kubernetes.io/gid: "11111"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ default "5Gi"  .Values.storageSize }}
      {{- if .Values.storageClass }}
      storageClassName:  {{ .Values.storageClass }}
      {{- end }}
  - metadata:
      name: backup
      annotations:
        pv.beta.kubernetes.io/gid: "11111"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ default "5Gi"  .Values.backupStorageSize }}
  {{- end }}
  template:
    metadata:
      labels:
        djInstance: {{ .Values.djInstance }}
        app: {{ template "fullname" . }}
        vendor: forgerock
        release: {{ .Release.Name }}
        component: opendj
    spec:
      affinity:
        podAntiAffinity:
        {{- if eq .Values.podAntiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: {{ .Values.topologyKey }}
            labelSelector:
                matchExpressions:
                - key: djInstance
                  operator: In
                  values:
                  - {{ .Values.djInstance }}
         {{- else if eq .Values.podAntiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: djInstance
                  operator: In
                  values:
                  - {{ .Values.djInstance }}
              topologyKey: {{ .Values.topologyKey }}
         {{- end }}
      terminationGracePeriodSeconds: 30
      # This will make sure the mounted PVCs are writable by the forgerock user with gid 111111.
      securityContext:
        fsGroup: 11111
      initContainers:
      {{- if (and .Values.gcs.enabled .Values.restore.enabled) }}
      # An example of restoring a previous backup from a google cloud storage bucket.
      # The bucket and path must exist, and the cluster needs --scopes storage-full when it is created.
      # This runs the gsutil command to rsync the contents of the bucket to the /backup folder
      - name: gcs
        #image: gcr.io/cloud-builders/gcloud:latest
        # For release we use a pinned version
        image: gcr.io/cloud-builders/gcloud@sha256:2030ade364a03a313926b169effc754e4b99867f05323a3d248354d3d1630dc0
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sh", "-c", "gsutil -m rsync -r {{ .Values.gcs.restoreBucket }} /backup; chmod -R g+rwx /backup"]
        volumeMounts:
        - name: backup
          mountPath: /backup
      {{- end }}
      # The restore init container restores data from a previous backup.
      {{ if .Values.restore.enabled }}
      - name: restore
        image:  {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: db
          mountPath: /opt/opendj/data
        - name: backup
          mountPath: /opt/opendj/bak
        - name: dj-secrets
          mountPath: /var/run/secrets/opendj
        envFrom:
        - configMapRef:
            name: {{ .Values.djInstance }}
        args: [ "restore-from-backup" ]
      {{ end }}
      # The setup init container is responsible for setting up DS if it is not configured or restored.
      - name: setup
        image:  {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: dj-secrets
          mountPath: /var/run/secrets/opendj
        - name: db
          mountPath: /opt/opendj/data
        envFrom:
        - configMapRef:
            name: {{ .Values.djInstance }}
        args: [ "setup" ]
      containers:
      - name: opendj
        image:  {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        envFrom:
        - configMapRef:
            name: {{ .Values.djInstance }}
        ports:
        - containerPort: 1389
          name: ldap
        - containerPort: 4444
          name: admin
        - containerPort: 8989
          name: replication
        - containerPort: 8080
          name: metrics
        volumeMounts:
        - name: dj-secrets
          mountPath: /var/run/secrets/opendj
        - name: backup
          mountPath: /opt/opendj/bak
        - name: logs
          mountPath: /opt/opendj/logs
        - name: db
          mountPath: /opt/opendj/data
        # Due to cost, we don't want to do a full scrape of the metrics http endpoint - so we create a tcp connection
        # todo: revisit when https://bugster.forgerock.org/jira/browse/OPENDJ-4728 is resolved.
        args: [ "start" ]
        readinessProbe:
          tcpSocket:
            port: metrics
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 60
      {{- if .Values.gcs.enabled }}
      # An example of enabling backup to google cloud storage.
      # The bucket and path must exist, and the cluster needs --scopes storage-full when it is created.
      # This runs the gsutil command periodically to rsync the contents of the /backup folder (shared with the DJ container) to cloud storage. 
      - name: backup
        #image: gcr.io/cloud-builders/gcloud
        # For release we use a pinned version
        image: gcr.io/cloud-builders/gcloud@sha256:2030ade364a03a313926b169effc754e4b99867f05323a3d248354d3d1630dc0
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sh", "-c",
            "while true; do gsutil -m rsync -r /backup {{ .Values.gcs.backupBucket }} ; sleep {{ .Values.gcs.sleepSeconds }};  done"]
        volumeMounts:
        - name: backup
          mountPath: /backup
      {{- end }}
      volumes:
      - name: dj-secrets
        secret:
          secretName: {{ .Values.djInstance }}
      - name: logs
        emptyDir: {}
      {{- if not .Values.djPersistence }}
      - name: backup
        emptyDir: {}
      - name: db
        emptyDir: {}
      {{ end }}