# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
# Secrets for OpenAM stack deployment. This will be mounted on all containers so they can get their
# passwords, etc.
# Note that secret values are base64-encoded.
# The base64-encoded value of 'password' is 'cGFzc3dvcmQ='.
# Watch for trailing \n when you encode!
apiVersion: v1
kind: Secret
metadata:
    name: {{ template "instanceName" . }}
type: Opaque
data:
  dirmanager.pw: {{ b64enc .Values.dirManagerPassword }}