# Gatling template for forgeops benchmark suite
# This is a YAML-formatted file.

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: forgeops-benchmark
  labels:
    vendor: forgerock
spec:
  template:
    metadata:
      labels:
        app: forgeops-benchmark
    spec:
      initContainers:
      {{ if eq .Values.config.strategy  "git" }}
      - name: git-init
        image: {{ .Values.gitImage.repository }}:{{ .Values.gitImage.tag }}
        imagePullPolicy: {{ .Values.gitImage.pullPolicy }}
        volumeMounts:
        - name: git
          mountPath: /git
        - name: git-secret
          mountPath: /etc/git-secret
        args: ["init"]
        envFrom:
        - configMapRef:
            name:  {{ default "frconfig" .Values.config.name  }}
      {{ end }}
      - name: forgeops-benchmark-gatling
        image: {{ .Values.image.repository }}
        imagePullPolicy: Always
        command:
          - /bin/bash
          - -c
          - cp -r /git/config/6.5/benchmarks/gatling-simulation-files/ /opt/gatling/user-files/simulations/ &&
            {{ if .Values.benchmark.runAfterDeployment }}touch /ready && {{ end }}
            /custom-gatling.sh  -j '
            -Dam_host={{ .Values.benchmark.openam.host }}
            -Dam_port={{ .Values.benchmark.openam.port }}
            -Dam_protocol={{ .Values.benchmark.openam.proto }}
            -Didm_host={{ .Values.benchmark.openidm.host }}
            -Didm_port={{ .Values.benchmark.openidm.port }}
            -Didm_protocol={{ .Values.benchmark.openidm.proto }}
            -Dig_host={{ .Values.benchmark.openig.host }}
            -Dig_port={{ .Values.benchmark.openig.port }}
            -Dig_protocol={{ .Values.benchmark.openig.proto }}
            -DlogoutPercent={{ .Values.benchmark.logoutpercent }}
            -Dusers={{ .Values.benchmark.users }}
            -Dconcurrency={{ .Values.benchmark.concurrency }}
            -Dduration={{ .Values.benchmark.duration }}
            -Dwarmup={{ .Values.benchmark.warmup }}
            -Dissue_token_info={{ .Values.benchmark.get_token_info }}
            -Doauth2_client_id={{ .Values.benchmark.oauth2_client_id }}
            -Doauth2_client_pw={{ .Values.benchmark.oauth2_client_pw }}
            '
            -g '-m -s {{ .Values.benchmark.testname }} -rd {{ .Values.benchmark.testname }}' &&
            export FN=$(ls -t /opt/gatling/results | head -1) && tar -czvf /opt/gatling/results/$FN.tar.gz
            /opt/gatling/results/$FN
        volumeMounts:
          - name: gatling-results
            mountPath: "/opt/gatling/results"
          {{ if eq .Values.config.strategy  "git" }}
          - name: git
            mountPath: /git
          {{ end }}
      containers:
        - name: forgeops-benchmark-results
          image: nginx:1.11.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: gatling-results
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf-vol
          resources:
      #resources:
      #  requests:
      #    cpu: 1000m
      #    memory: 2048Mi
      imagePullSecrets:
        - name: forgerock-engkube-pull-secret
      volumes:
      - name: nginx-conf-vol
        configMap:
          name: nginx-conf
      - name: gatling-results
        persistentVolumeClaim:
          claimName: forgeops-benchmark-pvc
      {{ if eq .Values.config.strategy  "git" }}
      - name: git
        emptyDir: {}
      - name: git-secret
        secret:
          secretName:  {{ default "frconfig" .Values.config.name }}
      {{ end }}
