# Gatling template for forgeops benchmark suite
# This is a YAML-formatted file.

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: forgeops-benchmark
  labels:
    vendor: forgerock
spec:
  template:
    metadata:
      labels:
        app: forgeops-benchmark
    spec:
      initContainers:
      - name: forgeops-benchmark-gatling
        image: {{ .Values.image.repository }}
        imagePullPolicy: Always
        command:
          - /bin/bash
          - -c
          - touch /ready && /custom-gatling.sh  -j '
            -Dam_host={{ .Values.benchmark.openam.host }}
            -Dam_port={{ .Values.benchmark.openam.port }}
            -DlogoutPercent={{ .Values.benchmark.logoutpercent }}
            -Dusers={{ .Values.benchmark.users }}
            -Dconcurrency={{ .Values.benchmark.concurrency }}
            -Dduration={{ .Values.benchmark.duration }}
            -Dwarmup={{ .Values.benchmark.warmup }}
            -Dissue_token_info={{ .Values.benchmark.get_token_info }}
            '
            -g '-m -s {{ .Values.benchmark.testname }} -rd {{ .Values.benchmark.testname }}' &&
            export FN=$(ls -t /opt/gatling/results | head -1) && tar -czvf /opt/gatling/results/$FN.tar.gz
            /opt/gatling/results/$FN
        volumeMounts:
          - mountPath: "/opt/gatling/results"
            name: gatling-results
      containers:
        - name: forgeops-benchmark-results
          image: nginx:1.11.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: gatling-results
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf-vol
          resources:
      #resources:
      #  requests:
      #    cpu: 1000m
      #    memory: 2048Mi
      imagePullSecrets:
        - name: forgerock-engkube-pull-secret
      volumes:
      - name: nginx-conf-vol
        configMap:
          name: nginx-conf
      - name: gatling-results
        persistentVolumeClaim:
          claimName: forgeops-benchmark-pvc
