# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
#
# Default values for OpenIG.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

domain: .example.com

# Configuration parameters. Common to all charts that require configuration from a
# source. Currently the only source is a git repo.
config:
  # Name of the configMap that holds the configuration repository URL and of
  # the secret required to access it.
  name: frconfig
  # Path to our project
  path: /git/config/6.5/default/ig/basic-sample
  # strategy defines how products get their configuration .
  # Using the git strategy, each helm chart pulls the configuration from git using an init container. 
  strategy: git


# Tomcat JVM options.
catalinaOpts: "-Xmx512m"
  
# To enable any of the products to use HTTPS on their external endpoint, set the following flag to true.
useTLS: false
# The default behaviour when useTLS = true, is to have cert-manager to manage the certificate request/renewal via Let's Encrypt.  
# This is enabled by the following flag:
useCertManager: true

image:
  repository: gcr.io/engineering-devops
  tag: 6.5.0
  pullPolicy: IfNotPresent

resources:
#  limits:
#    cpu: 1000m
#    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi

# These are both used to form the FQDN for the load balancer.  See _helpers.tpl
component: openig

service:
  name: openig
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

ingress:
  class: nginx
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # Do not use for nginx. TODO: Does warp need this?
    #ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/enable-cors: "false"
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    ingress.kubernetes.io/ssl-redirect: "true"
    # Nginx specific annotations
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    
# Audit log details for log streaming sidecar containers

auditLogs: []
# auditLogs:
#   - name: access-logs
#     path: "/tmp/logs/access.audit.json"
#   - name: debug-logs
#     path: "/tmp/logs/route-system.log"
    
    


