# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
#
# Default values for OpenIG.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

domain: .example.com

# Configuration parameters. Common to all charts that require configuration from a
# source. Currently the only source is a git repo.
config:
  # Path to our project
  path: /git/config/default/ig/basic-sample
  # The name of the configuration we want to use. This is used as a reference 
  # to either a pvc claim to mount that holds the configuration, or the name
  # is used to reference secrets and a configmap that is used to clone the git repo.
  # The default "frconfig" can be used when you want all products to share the same git repo. 
  # You can deploy multiple instances of the frconfig chart if you want per product repos.
  # for example,  helm install --set config.name=openig frconfig
  name: frconfig
  # strategy defines how products get their configuration .
  # Using the git strategy, each helm chart pulls the configuration from git using an init container. 
  strategy: git


# Tomcat JVM options.
catalinaOpts: "-Xmx512m"
  
# The default behavior is to use TLS and have cert-manager to manage the certificate request/renewal via Let's Encrypt.
# If you want to use TLS but don't want to cert-manager to manage the certificate request/renewal, then set
# useTLS to true, set useCertManager to false, and run the script ../bin/generate-tls.sh.
useTLS: true
useCertManager: true

image:
  repository: gcr.io/engineering-devops
  tag: 6.5.0
  pullPolicy: IfNotPresent

resources:
#  limits:
#    cpu: 1000m
#    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi

# These are both used to form the FQDN for the load balancer.  See _helpers.tpl
component: openig

service:
  name: openig
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

ingress:
  class: nginx
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # Do not use for nginx. TODO: Does warp need this?
    #ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/enable-cors: "false"
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    ingress.kubernetes.io/ssl-redirect: "true"
    # Nginx specific annotations
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    
    


