image:
  #repository: forgerock-docker-public.bintray.io/amster
  repository: gcr.io/engineering-devops/amster
  tag: 6.5.0-M0
  pullPolicy: Always
  
config:
  importPath: /git/config/6.0/m-cluster/am
  exportPath: /tmp/amster

ctsStores: ctsstore-0.ctsstore:1389,ctsstore-1.ctsstore:1389
ctsPassword: password


# For production set CPU limits to help Kube Schedule the pods.
resources:
 limits:
   memory: 756Mi
 requests:
   memory: 756Mi