domain: .frk8s.net

fqdn: openam.prod.frk8s.net

image:
  # repository: gcr.io/engineering-devops
  repository: forgerock-docker-public.bintray.io/forgerock
  tag: 6.5.0-M0
  pullPolicy: Always

# Note if you enable TLS then you have to either provide the certificate 
# by running generate-tls.sh script or you have to have cert-manager deployed
# for your DNS domain 
useTLS: true

# Only enable this if you have valid cert-manager deployed for your DNS domain
useCertManager: false
