image:
  #repository: forgerock-docker-public.bintray.io/ds
  repository: gcr.io/engineering-devops/ds
  tag: 6.5.0-M129.2-CTS-TTL
  pullPolicy: Always

instance: ctsstore

userstore:
  enabled: false

resources:
  limits:
    memory: 5Gi
  requests:
    memory: 3Gi

storageSize: 100Gi
storageClass: fast

# For JDK 8
opendjJavaArgs: >
  -server -Xms3g -Xmx3g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA 
  -XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps 
  -XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log

# For JDK 11
#opendjJavaArgs: >
#  -server -Xms3g -Xmx3g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA  
#  -XX:MaxGCPauseMillis=100 -verbose:gc -Xlog:gc:/tmp/gc.log


podAntiAffinity: hard

runPostSetupJob: false

replicas: 2

topologyKey: "failure-domain.beta.kubernetes.io/zone"