image:
  #repository: forgerock-docker-public.bintray.io/openidm
  repository: gcr.io/engineering-devops/openidm
  tag: 6.5.0-M0
  pullPolicy: Always
  
resources:
  limits:
    memory: 3Gi
  requests:
    memory: 2Gi

# For JDK 8
javaOpts: >
  -server -Xms2g -Xmx2g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA 
  -XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps 
  -XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log

replicaCount: 1

config:
  name: frconfig
  #path: /git/config/6.5/m-cluster/idm/ds-repo-explicit
  path: /git/config/6.5/default/idm/sync-with-ldap-bidirectional
  strategy: git