# Default values for openidm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# optional registry, including trailing /


# Used to form the FQDN  - see _helpers.tpl
component: openidm

replicaCount: 1

global:
  domain: .example.com
  git:
    # git repo to clone. The value below is a public git repo that does not require authentication.
    repo: "https://github.com/ForgeRock/forgeops-init.git"
    branch: master
  configPath:
    idm: default/idm/sync-with-ldap-bidirectional

image:
  repository: gcr.io/engineering-devops/openidm
  pullPolicy: IfNotPresent
  tag: 6.5.0-SNAPSHOT

# TODO: We should get the idmuser / password values from the secret created in the etc/gke/prepsql chart.
openidm:
  repo:
    host: localhost
    port: 5432
    user: idmuser
    password: idmpassword
    databaseName: idmuser
    schema: openidm

# Optional - if there is a DJ userstore configured
userstore:
  host: userstore-0.userstore
  password: password
  port: 1389

service:
  name: openidm
  type: NodePort
  externalPort: 80
  internalPort: 8080

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 300m
    memory: 1024Mi


# Set this to true if you want to include a psql sidecar container in the pod for debugging purposes.
debug: false

# Values: filebeat, none
logDriver: none


# Cloud SQL connection name
connectionName: "engineering-devops:us-central1:openidm1"

