# Sample value overrides for Helm. The values below will work out of the box, and
# are the same as the default values.yaml in the charts.
# To override these values, make a copy of this file, and pass it to helm with the -f option
# Example:  helm install -f my-custom.yaml openam
# *DO NOT* check your custom.values file into git, as it may contain ssh credentials. See below


# Global variables are used in all charts, including child charts nested under a parent chart.
# Refer to https://github.com/kubernetes/helm/blob/master/docs/charts.md#scope-dependencies-and-values for more information
# Be careful of proper yaml nesting here.
global:
  # The domain - including a leading dot '.'.  Product FQDNs are formed using this domain.
  # The format is  {component}.{kube-namespace}.{domain}.  For example: openam.default.example.com
  domain: .example.com
  # As an alternative to using fake domain names in /etc/hosts, you can use xip.io and your minikube IP address:
  # domain: .192.168.99.100.xip.io
  # Git Configuration:
  # Where to pull product configuration, or push it (pushing requires git ssh credentials)
  git:
    # git repo to clone. The value below is a public git repo that does not require authentication.
    repo: "https://stash.forgerock.org/scm/cloud/forgeops-init.git"
    # branch can be a git branch or a sha commit:
    branch: master
  # The relative path to the product configuration to import. Relative to /git/$projectDirectory/
  # specify the full path to the configuration
  configPath:
    idm:  default/idm/sync-with-ldap-bidirectional
    am:   default/am/empty-import
    ig:   default/ig/basic-sample
  # For AM only, you can specify a different export path. If this is not set, the export path defaults to  $configPath.am
  exportPath:
    am: default/am/autosave
  # Set this to true to use TLS for the ingresses for AM, IG, and IDM
  # If you set this to true, you must create the TLS secrets manually.
  # See bin/gen-ssl-secret.sh for an example of how to create a self-signed certificate.
  # Example command:   bin/gen-ssl-secret.sh openam.default.example.com
  # Will generate a self-signed certificate for the openam.default.example.com ingress.
  # The CN of the certificate *MUST* match the FQDN.
  useTLS: false
