apiVersion: apps/v1
kind: Deployment
metadata:
  name: amster
spec:
  replicas: 1
  template:
    spec:
      containers:
      - args:
        - configure
        - sync
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: amster
        - configMapRef:
            name: platform-config
        image: amster
        imagePullPolicy: IfNotPresent
        name: amster
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
            cpu: "100m"
        volumeMounts:
        - mountPath: /var/run/secrets/amster
          name: amster-secrets
          readOnly: true
      terminationGracePeriodSeconds: 5
      volumes:
      - name: amster-secrets
        secret:
          secretName: amster
      - name: platform-config
        configMap:
          name: platform-config
