namespace: default
resources:
  - ../../../base/kustomizeConfig
  - ../../../base/idm-cdk
  - ../../../base/7.0/ds/idrepo
  - ../../../base/ingress

patchesStrategicMerge:
- |-
  #Patch DS IDREPO
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ds-idrepo
  spec:
    replicas: 2
    template:
      spec:
        containers:
          - name: ds
            resources:
              requests:
                memory: 3Gi
                cpu: 2000m
              limits:
                memory: 5Gi
                cpu: 3000
        initContainers:
          - name: initialize
            imagePullPolicy: Always
    volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          pv.beta.kubernetes.io/gid: "0"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
        storageClassName: fast
